version: '3.9'
services:
  app:
    container_name: bamcoreport
    image: bamcoreport
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=amal
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bamDb